print('************')
print('*DESAFIO 01*')
print('************')
print('D1: Crie um script que leia o nome de uma pessoa e mostre uma mensagem de boas-vindas de acordo com o valor digitado.')
nome=input('Qual é o seu nome?')
print(nome,',é um prazer te conhecer! Seja muito Bem-Vindo(a)!')
print('____________________________________________________________')
print('************')
print('*DESAFIO 02*')
print('************')
print('D2: Crie um script que leia o dia, o mês e o ano de nascimento de uma pessoa e mostre uma mensagem com a data formatada.')
print('Registre os dados da data de seu nascimento abaixo:')
dia=input('Dia:')
mês=input('Mês:')
ano=input('Ano:')
print(nome,'você nasceu no dia',dia,'de',mês,'de',ano,',correto?')
print('_____________________________________________________________')
print('************')
print('*DESAFIO 03*')
print('************')
print('D3: Crie um scirpt que leia dois números e tente mostrar a soma entre eles.')
print(nome,',digite dois números para brincarmos de somar <3:')
n1=input('Primeiro número:')
n2=input('Segundo número:')
soma=int(n1)+int(n2)
print('Muito bem,',nome,'.A soma dos números escolhidos é=',soma)
